---
# TODO: BuildOut
# IAM Role: EC2_ECS_Access
- hosts: localhost
  vars:
    aws_region: us-east-1
  tasks:
    ### Network
    - name: SpyCloud Challenge
      ec2_vpc_net:
        name: SCVPC
        cidr_block: 10.10.0.0/16
        region: "{{aws_region}}"
        tags:
          module: ec2_vpc_net
          this: works
      register: spycloud_vpc

    - name: Create Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{ spycloud_vpc.vpc.id }}"
        region: "{{aws_region}}"
        state: present
      register: sc_igw

    - name: Create Public Subnet 1
      ec2_vpc_subnet:
        state: "present"
        vpc_id: "{{ spycloud_vpc.vpc.id }}"
        cidr: 10.10.16.0/20
        region: "{{aws_region}}"
        az: "{{aws_region}}a"
        tags:
          Name: "Resources 1"
        wait: true
      register: public_subnet1

    - name: Create Public Subnet 2
      ec2_vpc_subnet:
        state: "present"
        vpc_id: "{{ spycloud_vpc.vpc.id }}"
        cidr: 10.10.32.0/20
        region: "{{aws_region}}"
        az: "{{aws_region}}b"
        tags:
          Name: "Resources 2"
        wait: true
      register: public_subnet2

    - name: Create Public Route Table
      ec2_vpc_route_table:
        vpc_id: "{{spycloud_vpc.vpc.id}}"
        region: "{{aws_region}}"
        tags:
          Name: sc-public-route-table
        subnets:
        - "{{public_subnet1.subnet.id}}"
        - "{{public_subnet2.subnet.id}}"
        routes:
        - dest: "0.0.0.0/0"
          gateway_id: "{{sc_igw.gateway_id}}"

    - name: Create Private Subnet
      ec2_vpc_subnet:
        state: "present"
        vpc_id: "{{ spycloud_vpc.vpc.id }}"
        cidr: 10.10.0.0/20
        region: "{{aws_region}}"
        tags:
          Name: "Web App"
        wait: yes
      register: private_subnet

    - name: Create NAT gateway for Public Subnet 1
      ec2_vpc_nat_gateway:
        state: present
        subnet_id: "{{public_subnet1.subnet.id}}"
        wait: yes
        region: "{{aws_region}}"
        if_exist_do_not_create: true
      register: sc_ngw

    - name: Create Private Route Table
      ec2_vpc_route_table:
        vpc_id: "{{spycloud_vpc.vpc.id}}"
        region: "{{aws_region}}"
        tags:
          Name: sc-private-route-table
        subnets:
        - "{{private_subnet.subnet.id}}"
        routes:
        - dest: "0.0.0.0/0"
          gateway_id: "{{sc_ngw.nat_gateway_id}}"
      register: sc_private_route_table
    
      
    ### Security
    - name: example using security group rule descriptions
      ec2_group:
        name: SC_ECSClusterSecurityGroup
        description: "ECS Cluster Security Group"
        vpc_id: "{{spycloud_vpc.vpc.id}}"
        region: "{{aws_region}}"
        rules:
          - proto: tcp
            ports:
            - 80
            - 443
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80 and 443
      register: sc_ecscluster_sg
      
    # - name: Create new vpc endpoint with the default policy for ECS to register instances
      # command: aws ec2 create-vpc-endpoint \
        # --vpc-id  "{{spycloud_vpc.vpc.id}}" \
        # --vpc-endpoint-type Interface \
        # --service-name "{{ item }}" \
        # --subnet-id "{{private_subnet.subnet.id}}" \
        # --security-group-id "{{ sc_ecscluster_sg.group_id}}"
      # loop:
      # - com.amazonaws.us-east-1.ecs-agent
      # - com.amazonaws.us-east-1.ecs-telemetry
      # - com.amazonaws.us-east-1.ecs

    - name: Create EC2 Bastion
      ec2_instance:
        name: "sc_bastion"
        vpc_subnet_id: "{{public_subnet1.subnet.id}}"
        region: "{{aws_region}}"
        key_name: "DubSpyCloud"
        instance_type: "t2.micro"
        image_id: "ami-062f7200baf2fa504"
        network:
          assign_public_ip: true
        state: present
        wait: yes
      register: sc_bastion

    ### Loadbalacer
    - name: Create Target Group
      elb_target_group:
        name: "SC-ECSClusterTG"
        protocol: http
        port: 80
        vpc_id: "{{ spycloud_vpc.vpc.id }}"
        target_type: ip
        state: present
      register: sc_ecscluster_tg
        
    - name: Create Loadbalacer
      elb_application_lb:
        name: SC-ECSClusterLB
        security_groups:
          - "{{ sc_ecscluster_sg.group_id}}"
        subnets:
          - "{{public_subnet1.subnet.id}}"
          - "{{public_subnet2.subnet.id}}"
        listeners:
          - Protocol: HTTP
            Port: 80 
            DefaultActions:
              - Type: forward
                TargetGroupName: "{{sc_ecscluster_tg.target_group_name}}"
        state: present

    - name: Create ECS Cluster
      ecs_cluster:
        name: sc-prod-cluster
        region: "{{aws_region}}"
        state: present
      register: sc_cluster

    - name: Create EC2 Instance for Cluster
      ec2_instance:
        name: "sc_ecs_host"
        vpc_subnet_id: "{{private_subnet.subnet.id}}"
        region: "{{aws_region}}"
        key_name: "DubSpyCloud"
        instance_type: "t2.micro"
        instance_role: EC2_ECS_Access
        image_id: "ami-07a63940735aebd38"
        security_group: "{{ sc_ecscluster_sg.group_name}}"
        user_data: |
                  #!/bin/bash
                  echo ECS_CLUSTER={{sc_cluster.cluster.clusterName}} >> /etc/ecs/ecs.config
        wait: yes
        state: present
        tags:
          Name: "sc_ecs_host"
      register: sc_ecs_host

    - name: sleep to let EC2 instance connect to ECS Cluster
      wait_for:
        timeout: 30
      delegate_to: localhost
