---
- hosts: webservers
  become: yes
  tasks:
#  - name: Install Nginx
#    yum:
  - name: Create task definition
    ecs_taskdefinition:
      family: nginx
      containers:
      - name: nginx
        essential: true
        image: "nginx"
        portMappings:
        - containerPort: 8080
          hostPort:      8080
        cpu: 512
        memory: 1024
      state: present